-- Amorcage du catalogue Radia Glam Academy (formations en BROUILLON, publie=false).
-- Idempotent : ON CONFLICT (id) DO NOTHING. La proprietaire relit puis publie
-- chaque formation depuis /admin/formations. IDs stables prefixes "seed_".

-- ===================== FORMATIONS =====================
INSERT INTO "Formation"
  (id, titre, description, programme, duree, "tarifFcfa", niveau, photos, publie,
   categorie, mode, promesse, objectifs, "pourQui", inclus, "dureeVideo", "ordreAffichage")
VALUES
(
  'seed_auto_maquillage',
  'Auto-maquillage',
  'Apprenez a vous maquiller vous-meme comme une professionnelle, meme sans experience.',
  'Materiel, preparation de peau, teint, yeux, levres, looks jour et soiree, longue tenue.',
  '15 modules', 40000, 'Debutant', ARRAY[]::TEXT[], false,
  'MAQUILLAGE'::"CategorieFormation", 'EN_LIGNE'::"ModeFormation",
  'Maitrisez votre propre maquillage, du teint naturel au look de soiree, a votre rythme.',
  ARRAY['Choisir le bon materiel','Preparer sa peau','Comprendre sa carnation et son sous-ton','Realiser un teint naturel','Maquiller ses yeux et ses levres','Faire tenir son maquillage toute la journee'],
  ARRAY['Vous voulez apprendre a vous maquiller vous-meme','Vous debutez totalement','Vous voulez un resultat naturel et maitrise au quotidien'],
  ARRAY['Videos etape par etape','Supports PDF telechargeables','Liste des produits adaptes a differents budgets','Guide des teintes','Certificat de fin de formation','Acces personnel a la plateforme'],
  'Environ 4h de videos', 1
),
(
  'seed_makeup_starter',
  'Makeup Starter',
  'Apprendre a se maquiller de zero : les fondamentaux du maquillage, sans connaissance prealable.',
  'Materiel, preparation, teint, poudres, sourcils, yeux, contouring, levres, makeup complet.',
  '10 modules', 50000, 'Debutant', ARRAY[]::TEXT[], false,
  'MAQUILLAGE'::"CategorieFormation", 'EN_LIGNE'::"ModeFormation",
  'Les bases techniques du maquillage pour partir de zero et realiser un makeup complet.',
  ARRAY['Connaitre le materiel indispensable','Preparer la peau','Reussir un teint equilibre','Structurer sourcils et regard','Maitriser contouring et blush','Realiser un maquillage complet etape par etape'],
  ARRAY['Vous debutez et voulez des bases solides','Vous voulez apprendre les techniques, pas seulement vous depanner','Vous envisagez peut-etre d''en faire un metier plus tard'],
  ARRAY['Videos etape par etape','Support PDF recapitulatif','Liste des produits','Exercices pratiques','Certificat de fin de formation','Acces personnel a la plateforme'],
  'Environ 3h de videos', 2
),
(
  'seed_architecte_teint',
  'Architecte du Teint',
  'La formation signature Radiaglam : maitriser le teint professionnel, lumineux et longue tenue, adapte a chaque carnation.',
  'Comprendre et preparer la peau, sous-tons, choix et melange des teintes, correction, contouring, poudrage, teint longue tenue.',
  '16 modules', 100000, 'Perfectionnement', ARRAY[]::TEXT[], false,
  'MAQUILLAGE'::"CategorieFormation", 'EN_LIGNE'::"ModeFormation",
  'La methode Radiaglam pour realiser un teint professionnel, lumineux et longue tenue, particulierement adapte aux peaux noires.',
  ARRAY['Preparer parfaitement la peau','Identifier les sous-tons et choisir la bonne teinte','Corriger les imperfections et hyperpigmentations','Construire le teint sans effet masque','Obtenir un teint lumineux et longue tenue','Adapter le teint a chaque carnation'],
  ARRAY['Vous voulez un teint parfait sur toutes les peaux','Vous maitrisez deja quelques bases','Vous etes maquilleuse et voulez perfectionner votre teint'],
  ARRAY['Videos etape par etape','Guide des sous-tons','Fiche de diagnostic de peau','Liste des produits recommandes','Certificat de fin de formation','Acces personnel a la plateforme'],
  'Environ 5h de videos', 3
),
(
  'seed_black_skin',
  'Black Skin Makeup',
  'Comprendre, corriger et sublimer les peaux noires et metissees : une veritable specialisation.',
  'Carnations, sous-tons, choix du fond de teint, correction, hyperpigmentation, poudres, bronzer, blush, couleurs, demonstrations.',
  '15 modules', 100000, 'Specialisation', ARRAY[]::TEXT[], false,
  'MAQUILLAGE'::"CategorieFormation", 'EN_LIGNE'::"ModeFormation",
  'L''expertise des peaux noires et metissees : comprendre, corriger et sublimer toutes les carnations.',
  ARRAY['Comprendre les differentes carnations','Choisir le bon fond de teint','Corriger les zones sombres et l''hyperpigmentation','Eviter le teint gris ou cendre','Adapter bronzer, blush et couleurs','Realiser un maquillage naturel comme glamour'],
  ARRAY['Vous travaillez sur des peaux noires et metissees','Vous voulez une vraie expertise differenciante','Vous cherchez a corriger les erreurs frequentes de teint'],
  ARRAY['Videos etape par etape','Supports PDF','Liste des produits recommandes','Demonstrations sur plusieurs carnations','Certificat de fin de formation','Acces personnel a la plateforme'],
  'Environ 4h30 de videos', 4
),
(
  'seed_makeup_pro',
  'Makeup Pro',
  'Devenir maquilleuse professionnelle : une formation complete, du metier a la realisation.',
  'Metier, materiel, hygiene, analyse du visage, teint pro, correction, yeux, mariee, evenementiel, portfolio.',
  '20 modules', 150000, 'Professionnel', ARRAY[]::TEXT[], false,
  'PERFECTIONNEMENT'::"CategorieFormation", 'EN_LIGNE'::"ModeFormation",
  'De la passion au metier : tout pour devenir maquilleuse professionnelle et gerer vos prestations.',
  ARRAY['Comprendre le metier et son organisation','Maitriser hygiene et preparation de peau','Realiser un teint professionnel','Maitriser correction, contouring et techniques yeux','Reussir un maquillage mariee et evenementiel','Construire son portfolio et gerer ses prestations'],
  ARRAY['Vous voulez faire du maquillage votre metier','Vous avez deja des bases et voulez passer au niveau pro','Vous voulez travailler avec de vraies clientes'],
  ARRAY['Videos etape par etape','Supports PDF et fiches pratiques','Liste du materiel professionnel','Exercices et cas pratiques','Certificat de fin de formation','Acces personnel a la plateforme'],
  'Environ 7h30 de videos', 5
),
(
  'seed_makeup_business',
  'Makeup Business',
  'De maquilleuse a entrepreneure : transformer une competence en activite professionnelle rentable.',
  'Positionnement, tarifs, couts, clientele, portfolio, reseaux sociaux, fidelisation, marque, equipe.',
  '18 modules', 100000, 'Business', ARRAY[]::TEXT[], false,
  'BUSINESS'::"CategorieFormation", 'EN_LIGNE'::"ModeFormation",
  'De maquilleuse a entrepreneure : construisez une activite qui vous fait vivre de votre metier.',
  ARRAY['Construire son identite et son positionnement','Fixer ses tarifs et calculer ses couts','Trouver et fideliser ses clientes','Creer son portfolio et son contenu','Utiliser Instagram sans etre en promotion constante','Developper son activite et sa marque'],
  ARRAY['Vous savez maquiller mais peinez a en vivre','Vous voulez structurer et developper votre activite','Vous voulez construire une vraie marque personnelle'],
  ARRAY['Videos etape par etape','Modele de grille tarifaire','Fiche cliente et checklist prestation','Calendrier de contenu','Certificat de fin de formation','Acces personnel a la plateforme'],
  'Environ 5h de videos', 6
)
ON CONFLICT (id) DO NOTHING;

-- ===================== MODULES (LECONS) =====================
INSERT INTO "Lecon" (id, "formationId", titre, ordre) VALUES
-- Auto-maquillage
('seed_auto_01','seed_auto_maquillage','Bien choisir son materiel',1),
('seed_auto_02','seed_auto_maquillage','Preparer sa peau',2),
('seed_auto_03','seed_auto_maquillage','Comprendre sa carnation et son sous-ton',3),
('seed_auto_04','seed_auto_maquillage','Choisir son fond de teint et son correcteur',4),
('seed_auto_05','seed_auto_maquillage','Realiser un teint naturel',5),
('seed_auto_06','seed_auto_maquillage','Sourcils',6),
('seed_auto_07','seed_auto_maquillage','Maquillage des yeux facile',7),
('seed_auto_08','seed_auto_maquillage','Eyeliner et mascara',8),
('seed_auto_09','seed_auto_maquillage','Contouring, bronzer et blush',9),
('seed_auto_10','seed_auto_maquillage','Maquillage des levres',10),
('seed_auto_11','seed_auto_maquillage','Look journee',11),
('seed_auto_12','seed_auto_maquillage','Transformer son look en maquillage soiree',12),
('seed_auto_13','seed_auto_maquillage','Maquillage longue tenue',13),
('seed_auto_14','seed_auto_maquillage','Les erreurs a eviter',14),
('seed_auto_15','seed_auto_maquillage','Makeup complet etape par etape',15),
-- Makeup Starter
('seed_starter_01','seed_makeup_starter','Introduction et materiel',1),
('seed_starter_02','seed_makeup_starter','Preparation de la peau',2),
('seed_starter_03','seed_makeup_starter','Teint : fond de teint et correcteur',3),
('seed_starter_04','seed_makeup_starter','Poudres et fixation',4),
('seed_starter_05','seed_makeup_starter','Sourcils',5),
('seed_starter_06','seed_makeup_starter','Maquillage des yeux',6),
('seed_starter_07','seed_makeup_starter','Eyeliner et mascara',7),
('seed_starter_08','seed_makeup_starter','Contouring et blush',8),
('seed_starter_09','seed_makeup_starter','Levres',9),
('seed_starter_10','seed_makeup_starter','Maquillage complet etape par etape',10),
-- Architecte du Teint
('seed_teint_01','seed_architecte_teint','Comprendre la peau',1),
('seed_teint_02','seed_architecte_teint','Preparer la peau',2),
('seed_teint_03','seed_architecte_teint','Identifier les sous-tons',3),
('seed_teint_04','seed_architecte_teint','Choisir la bonne teinte',4),
('seed_teint_05','seed_architecte_teint','Melanger les teintes',5),
('seed_teint_06','seed_architecte_teint','Fond de teint : couvrance et texture',6),
('seed_teint_07','seed_architecte_teint','Correcteurs',7),
('seed_teint_08','seed_architecte_teint','Neutralisation des hyperpigmentations',8),
('seed_teint_09','seed_architecte_teint','Teint sur peau noire',9),
('seed_teint_10','seed_architecte_teint','Contouring et bronzer',10),
('seed_teint_11','seed_architecte_teint','Blush',11),
('seed_teint_12','seed_architecte_teint','Poudrage',12),
('seed_teint_13','seed_architecte_teint','Teint lumineux',13),
('seed_teint_14','seed_architecte_teint','Teint longue tenue',14),
('seed_teint_15','seed_architecte_teint','Les erreurs qui vieillissent le teint',15),
('seed_teint_16','seed_architecte_teint','Realisation complete - methode Radiaglam',16),
-- Black Skin Makeup
('seed_black_01','seed_black_skin','Comprendre les differentes carnations',1),
('seed_black_02','seed_black_skin','Sous-tons des peaux noires',2),
('seed_black_03','seed_black_skin','Choisir son fond de teint',3),
('seed_black_04','seed_black_skin','Corriger les zones sombres',4),
('seed_black_05','seed_black_skin','Hyperpigmentation',5),
('seed_black_06','seed_black_skin','Teint gris ou cendre : pourquoi et comment eviter',6),
('seed_black_07','seed_black_skin','Poudres adaptees',7),
('seed_black_08','seed_black_skin','Bronzer sur peau noire',8),
('seed_black_09','seed_black_skin','Blush sur peau noire',9),
('seed_black_10','seed_black_skin','Highlighter',10),
('seed_black_11','seed_black_skin','Couleurs de fards',11),
('seed_black_12','seed_black_skin','Couleurs de levres',12),
('seed_black_13','seed_black_skin','Maquillage naturel',13),
('seed_black_14','seed_black_skin','Maquillage glamour',14),
('seed_black_15','seed_black_skin','Demonstration complete',15),
-- Makeup Pro
('seed_pro_01','seed_makeup_pro','Le metier de maquilleuse',1),
('seed_pro_02','seed_makeup_pro','Organisation de son materiel',2),
('seed_pro_03','seed_makeup_pro','Hygiene et desinfection',3),
('seed_pro_04','seed_makeup_pro','Preparation de differents types de peau',4),
('seed_pro_05','seed_makeup_pro','Analyse du visage',5),
('seed_pro_06','seed_makeup_pro','Teint professionnel',6),
('seed_pro_07','seed_makeup_pro','Correction et camouflage',7),
('seed_pro_08','seed_makeup_pro','Contouring',8),
('seed_pro_09','seed_makeup_pro','Sourcils professionnels',9),
('seed_pro_10','seed_makeup_pro','Techniques yeux',10),
('seed_pro_11','seed_makeup_pro','Faux-cils',11),
('seed_pro_12','seed_makeup_pro','Maquillage evenementiel',12),
('seed_pro_13','seed_makeup_pro','Maquillage mariee',13),
('seed_pro_14','seed_makeup_pro','Adaptation aux differentes carnations',14),
('seed_pro_15','seed_makeup_pro','Realisation d un makeup complet',15),
('seed_pro_16','seed_makeup_pro','Les erreurs de debutante',16),
('seed_pro_17','seed_makeup_pro','Organisation d une prestation',17),
('seed_pro_18','seed_makeup_pro','Relation avec la cliente',18),
('seed_pro_19','seed_makeup_pro','Photographier son travail',19),
('seed_pro_20','seed_makeup_pro','Construire son portfolio',20),
-- Makeup Business
('seed_biz_01','seed_makeup_business','Passer de passionnee a professionnelle',1),
('seed_biz_02','seed_makeup_business','Construire son identite',2),
('seed_biz_03','seed_makeup_business','Choisir son positionnement',3),
('seed_biz_04','seed_makeup_business','Definir ses prestations',4),
('seed_biz_05','seed_makeup_business','Fixer ses tarifs',5),
('seed_biz_06','seed_makeup_business','Calculer ses couts',6),
('seed_biz_07','seed_makeup_business','Organiser ses rendez-vous',7),
('seed_biz_08','seed_makeup_business','Gerer ses clientes',8),
('seed_biz_09','seed_makeup_business','Creer son portfolio',9),
('seed_biz_10','seed_makeup_business','Instagram et contenu',10),
('seed_biz_11','seed_makeup_business','Se vendre sans etre en promotion constante',11),
('seed_biz_12','seed_makeup_business','Attirer ses premieres clientes',12),
('seed_biz_13','seed_makeup_business','Fideliser',13),
('seed_biz_14','seed_makeup_business','Collaborations',14),
('seed_biz_15','seed_makeup_business','Organisation financiere',15),
('seed_biz_16','seed_makeup_business','Developper son activite',16),
('seed_biz_17','seed_makeup_business','Recruter et travailler avec une equipe',17),
('seed_biz_18','seed_makeup_business','Construire une vraie marque',18)
ON CONFLICT (id) DO NOTHING;

-- ===================== PARAMETRES PASS =====================
INSERT INTO "ContenuSite" (id, cle, valeur, "updatedAt") VALUES
('seed_pass_prix','pass_prix','299000', now()),
('seed_pass_duree','pass_duree_mois','12', now()),
('seed_pass_desc','pass_description','Acces a toutes les formations en ligne de Radia Glam Academy pendant 12 mois.', now())
ON CONFLICT (cle) DO NOTHING;
